#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""DLDS-I020 — clean tree gate.

At the end of a wave, `git status` must be clean, or every dirty path must carry
an explicit owner and task. A dirty path nobody claims is how work gets lost and
how an unverified change reaches a branch unnoticed.

Attribution comes from the recorded authority artifacts, never from a guess:

* the path is listed in `reports/current/DEEPSEEK-WORKTREE-INVENTORY.json` (the
  attribution record for the previous round's delta), or
* the path is a generated projection (`reports/current/**`,
  `design-lab/config/current-report-index.json`, `design-lab/config/repository-size-report.json`,
  `design-lab/config/rights-registry.json`), or
* the caller passes `--allow <prefix> --reason <text>` for a path this run owns.

Writes reports/current/CLEAN-TREE-REPORT.json.

Usage:
    python scripts/verify_clean_tree.py
    python scripts/verify_clean_tree.py --allow src/design_lab/creative/ --reason "DLDS-F030 in flight"
"""
from __future__ import annotations

import argparse
import json
import subprocess
from datetime import datetime, timezone
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
OUT = REPO / "reports/current/CLEAN-TREE-REPORT.json"
TASK_KEY = "DL-TP-20260914-DEEPSEEK-AUTHORITY-R1::DLDS-I020"
GENERATED_PREFIXES = ("reports/current/",)
GENERATED_EXACT = ("design-lab/config/current-report-index.json",
                   "design-lab/config/repository-size-report.json",
                   "design-lab/config/rights-registry.json")


def git(*args: str) -> str:
    return subprocess.run(["git", "-C", str(REPO), *args], capture_output=True, text=True,
                          encoding="utf-8", errors="replace").stdout


def attributed_paths() -> set:
    inventory = REPO / "reports/current/DEEPSEEK-WORKTREE-INVENTORY.json"
    if not inventory.is_file():
        return set()
    document = json.loads(inventory.read_text(encoding="utf-8"))
    return {entry["path"] for entry in document.get("entries", [])}


def main(argv=None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--allow", action="append", default=[])
    parser.add_argument("--reason", default="")
    args = parser.parse_args(argv)
    porcelain = [line for line in git("status", "--porcelain=v1").splitlines() if line.strip()]
    known = attributed_paths()
    rows, unattributed = [], []
    for line in porcelain:
        status, _, path = line[:2].strip(), line[2:], line[3:].strip()
        if " -> " in path:  # a rename reports both sides
            path = path.split(" -> ", 1)[1]
        generated = path.startswith(GENERATED_PREFIXES) or path in GENERATED_EXACT
        if path in known:
            owner, why = "attributed by DLDS-A030/A040", "listed in the worktree inventory"
        elif generated:
            owner, why = "generated projection", "regenerated by its own generator"
        elif any(path.startswith(prefix) for prefix in args.allow):
            owner, why = "this run", args.reason or "declared with --allow"
        else:
            owner, why = None, None
            unattributed.append(path)
        rows.append({"path": path, "status": status, "owner": owner, "reason": why,
                     "generated": generated})
    document = {
        "schemaVersion": "design-lab/clean-tree-report/v1",
        "task_key": TASK_KEY,
        "checked_at": datetime.now(timezone.utc).isoformat(timespec="seconds"),
        "subject_sha": git("rev-parse HEAD").strip(),
        "branch": git("rev-parse", "--abbrev-ref", "HEAD").strip(),
        "clean": not porcelain,
        "dirty_paths": len(porcelain),
        "rows": rows,
        "unattributed": unattributed,
        "allow_rules": args.allow,
        "verdict": "CLEAN" if not porcelain else ("ATTRIBUTED" if not unattributed else "UNATTRIBUTED"),
        "rule": "a dirty path is acceptable only with a named owner and task; an unattributed "
                "path fails the gate",
    }
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps(document, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
    print(f"CLEAN_TREE={document['verdict']} dirty={len(porcelain)} unattributed={len(unattributed)}")
    for path in unattributed:
        print("  UNATTRIBUTED:", path)
    return 0 if not unattributed else 1


if __name__ == "__main__":
    raise SystemExit(main())
